version: '3.7'

services:
  web:
    build: ./epanet
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./epanet/:/usr/src/app/
      - ./grafana-provisioning/:/usr/src/app/grafana-provisioning
    ports:
      - 8000:8000
    env_file:
      - .env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kios
      - POSTGRES_PASSWORD=kios1234!
      - POSTGRES_DB=virtual_city
  influxdb:
    image: influxdb:1.8.4-alpine
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=virtual_city
      - INFLUXDB_ADMIN_USER=kios
      - INFLUXDB_ADMIN_PASSWORD=kios1234!
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
volumes:
  postgres_data:
  grafana_data:
  influxdb-storage: