{
 "title": "Water Sensors BaSP",
 "time": { "from": "2021-01-01T01:39:50.820Z", "to": "2021-01-08T08:26:32.963Z" },
 "templating": {
  "list": [
   {
    "name": "Pressure_Sensors",
    "query": "\nSHOW TAG VALUES FROM \"water_output_test1_scada_sensors\" WITH KEY =\"sensorid\" WHERE (\"sensortype\" = 'pressure' )\n"
   },
   {
    "name": "Demand_Sensors",
    "query": "SHOW TAG VALUES FROM \"water_output_test1_scada_sensors\" WITH KEY =\"sensorid\" WHERE (\"sensortype\" = 'demand' )"
   },
   {
    "name": "Flow_Sensors",
    "query": "SHOW TAG VALUES FROM \"water_output_test1_scada_sensors\" WITH KEY =\"sensorid\" WHERE (\"sensortype\" = 'flow' )"
   },
   {
    "name": "Sensor_Type",
    "query": "SHOW TAG VALUES FROM \"water_output_test1_scada_sensors\" WITH KEY =\"sensortype\" "
   }
  ]
 },
 "panels": [
  {
   "title": "$Pressure_Sensors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "water_output_test1_scada_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE $timeFilter GROUP BY \"sensorid\", \"sensortype\"",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Pressure_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Pressure_Sensors minimum pressure per day",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "water_output_test1_scada_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE $timeFilter GROUP BY \"sensorid\", \"sensortype\"",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Pressure_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Pressure_Sensors location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "long" ], "type": "tag" },
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "water_output_test1_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE (\"sensorid\" =~ /^$Pressure_Sensors$/)  GROUP BY \"lat\", \"long\", \"sensorid\"",
     "select": [
      [
       { "params": [ "resolution" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Pressure_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Flow_Sensors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "water_output_test1_scada_sensors",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Flow_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Flow_Sensors minimum flow per day",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "water_output_test1_scada_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE $timeFilter GROUP BY \"sensorid\", \"sensortype\"",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Flow_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Flow_Sensors location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "long" ], "type": "tag" },
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "water_output_test1_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE (\"sensorid\" =~ /^$Flow_Sensors$/)  GROUP BY \"lat\", \"long\", \"sensorid\"",
     "select": [
      [
       { "params": [ "resolution" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Pressure_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Demand_Sensors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "water_output_test1_scada_sensors",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Demand_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Demand_Sensors maximum hourly consuption per day",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "water_output_test1_scada_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE $timeFilter GROUP BY \"sensorid\", \"sensortype\"",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Demand_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "$Demand_Sensors location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "long" ], "type": "tag" },
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "water_output_test1_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE (\"sensorid\" =~ /^$Demand_Sensors$/)  GROUP BY \"lat\", \"long\", \"sensorid\"",
     "select": [
      [
       { "params": [ "resolution" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensorid", "operator": "=~", "value": "/^$Pressure_Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Smart Virtual City",
   "type": "text",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "options": {
    "content": " <img src=\"https://mariosmsk.com/wp-content/uploads/2020/12/sssss.png\" style=\"width:1120px;height:360px;\"/> \n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_timestamp AS \"time\",\n  sensor_value\nFROM water_output_test1_scada_sensors\nWHERE\n  $__timeFilter(reading_timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sensor Locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 15 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "long" ], "type": "tag" },
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "water_output_test1_sensors",
     "query": "SELECT \"resolution\" FROM \"water_output_test1_sensors\" WHERE (\"sensortype\" =~ /^$Sensor_Type$/)  GROUP BY \"lat\", \"long\", \"sensorid\"",
     "select": [
      [
       { "params": [ "resolution" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensortype", "operator": "=~", "value": "/^$Se_nsor_Type$/" }
     ]
    }
   ]
  },
  {
   "title": "$Sensor_Type sensors statistics",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "sensorid" ], "type": "tag" }
     ],
     "measurement": "water_output_test1_scada_sensors",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "sensortype", "operator": "=~", "value": "/^$Sensor_Type$/" }
     ]
    }
   ]
  }
 ]
}